Remove python 3.7 support
It doesn't support typing.Literal
>  ImportError: cannot import name 'Literal' from 'typing'
https://github.com/jamiekt/jstark/actions/runs/3475068083/jobs/5808896337\#step:7:76